export const MOCK_USERS = [
  {
    id: '1',
    username: 'sarah_jones',
    full_name: 'Sarah Jones',
    bio: 'Travel lover | Coffee addict | Entrepreneur',
    avatar_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    cover_url: 'https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Kampala, Uganda',
    country: 'Uganda',
    is_verified: true,
    is_premium: true,
    interests: ['Travel', 'Business', 'Fitness'],
    looking_for: ['Friends', 'Networking'],
    coins: 2400,
    points: 1850,
    reputation_score: 92,
    is_online: true,
    followers: 1208,
    following: 380,
  },
  {
    id: '2',
    username: 'alex_wright',
    full_name: 'Alex Wright',
    bio: 'Software engineer & startup founder. Building the future.',
    avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Nairobi, Kenya',
    is_verified: true,
    is_premium: false,
    interests: ['Technology', 'Gaming', 'Music'],
    looking_for: ['Friends', 'Networking', 'Mentorship'],
    coins: 800,
    points: 2100,
    is_online: false,
    followers: 543,
    following: 210,
  },
  {
    id: '3',
    username: 'priya_sharma',
    full_name: 'Priya Sharma',
    bio: 'Fitness coach | Mental health advocate | Dog mom',
    avatar_url: 'https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Lagos, Nigeria',
    is_verified: false,
    is_premium: true,
    interests: ['Fitness', 'Art', 'Travel'],
    looking_for: ['Friends', 'Dating'],
    coins: 1200,
    points: 900,
    is_online: true,
    followers: 3400,
    following: 890,
  },
  {
    id: '4',
    username: 'marcus_chen',
    full_name: 'Marcus Chen',
    bio: 'Product designer. Creating experiences people love.',
    avatar_url: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Accra, Ghana',
    is_verified: true,
    is_premium: false,
    interests: ['Art', 'Technology', 'Music'],
    looking_for: ['Networking', 'Friends'],
    coins: 340,
    points: 1450,
    is_online: true,
    followers: 892,
    following: 456,
  },
  {
    id: '5',
    username: 'amina_diallo',
    full_name: 'Amina Diallo',
    bio: 'Entrepreneur | Mentor | Passionate about Africa',
    avatar_url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Dakar, Senegal',
    is_verified: true,
    is_premium: true,
    interests: ['Business', 'Travel', 'Art'],
    looking_for: ['Networking', 'Mentorship'],
    coins: 5600,
    points: 3200,
    is_online: false,
    followers: 8900,
    following: 220,
  },
  {
    id: '6',
    username: 'james_okafor',
    full_name: 'James Okafor',
    bio: 'Music producer | Creative director | Storyteller',
    avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Abuja, Nigeria',
    is_verified: false,
    is_premium: false,
    interests: ['Music', 'Art', 'Sports'],
    looking_for: ['Friends', 'Dating'],
    coins: 120,
    points: 650,
    is_online: true,
    followers: 2100,
    following: 780,
  },
];

export const MOCK_POSTS = [
  {
    id: '1',
    user: MOCK_USERS[0],
    content: 'Just got back from an incredible 3-week trip through East Africa. The connections I made along the way were absolutely priceless. Thank you PARENE for helping me find my travel companions! 🌍',
    media_urls: ['https://images.pexels.com/photos/1308881/pexels-photo-1308881.jpeg?auto=compress&cs=tinysrgb&w=800'],
    post_type: 'photo',
    categories: ['Travel', 'Relationships'],
    likes_count: 284,
    comments_count: 47,
    shares_count: 18,
    saves_count: 92,
    is_liked: true,
    is_saved: false,
    created_at: '2h ago',
  },
  {
    id: '2',
    user: MOCK_USERS[1],
    content: 'Just closed our seed round! Grateful for all the mentors and advisors I connected with here on PARENE. The startup journey is tough but having the right people around makes all the difference. Who else is building something amazing? Drop your startup in the comments!',
    post_type: 'text',
    categories: ['Business', 'Entrepreneurship'],
    likes_count: 521,
    comments_count: 89,
    shares_count: 43,
    saves_count: 167,
    is_liked: false,
    is_saved: true,
    created_at: '4h ago',
  },
  {
    id: '3',
    user: MOCK_USERS[2],
    content: 'Morning workout complete! 5km run + 45min strength training. Remember: your body is your greatest investment. Anyone want a free 30-day fitness challenge? I am starting one next Monday!',
    media_urls: ['https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800'],
    post_type: 'photo',
    categories: ['Fitness', 'Health'],
    likes_count: 893,
    comments_count: 156,
    shares_count: 67,
    saves_count: 412,
    is_liked: true,
    is_saved: false,
    created_at: '6h ago',
  },
  {
    id: '4',
    user: MOCK_USERS[3],
    content: 'Design tip of the day: White space is not empty space — it is breathing room. Give your designs room to breathe and your users room to think.',
    post_type: 'text',
    categories: ['Design', 'Technology'],
    likes_count: 347,
    comments_count: 28,
    shares_count: 91,
    saves_count: 223,
    is_liked: false,
    is_saved: false,
    created_at: '8h ago',
  },
  {
    id: '5',
    user: MOCK_USERS[4],
    content: 'Relationship advice: The quality of your relationships determines the quality of your life. Invest in people who invest in you. Protect your peace. Build your circle intentionally.',
    post_type: 'text',
    categories: ['Relationships', 'Personal Growth'],
    likes_count: 1204,
    comments_count: 203,
    shares_count: 445,
    saves_count: 876,
    is_liked: true,
    is_saved: true,
    created_at: '12h ago',
  },
];

export const MOCK_STORIES = [
  { id: '1', user: MOCK_USERS[0], viewed: false },
  { id: '2', user: MOCK_USERS[1], viewed: false },
  { id: '3', user: MOCK_USERS[2], viewed: true },
  { id: '4', user: MOCK_USERS[3], viewed: false },
  { id: '5', user: MOCK_USERS[4], viewed: true },
  { id: '6', user: MOCK_USERS[5], viewed: false },
];

export const MOCK_COMMUNITIES = [
  {
    id: '1',
    name: 'Entrepreneurs Uganda',
    description: 'A community for startup founders and entrepreneurs across Uganda and East Africa.',
    cover_url: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Business',
    members_count: 8420,
    posts_count: 2340,
    is_featured: true,
    is_paid: false,
    is_joined: true,
  },
  {
    id: '2',
    name: 'Fitness & Wellness Circle',
    description: 'Transform your body and mind with expert coaches and a supportive community.',
    cover_url: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Fitness',
    members_count: 15600,
    posts_count: 8900,
    is_featured: true,
    is_paid: false,
    is_joined: false,
  },
  {
    id: '3',
    name: 'Travelers of Africa',
    description: 'Explore the beauty of Africa with fellow adventurers. Share routes, tips, and experiences.',
    cover_url: 'https://images.pexels.com/photos/2082103/pexels-photo-2082103.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/2416653/pexels-photo-2416653.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Travel',
    members_count: 12300,
    posts_count: 5670,
    is_featured: false,
    is_paid: false,
    is_joined: true,
  },
  {
    id: '4',
    name: 'Tech Developers Hub',
    description: 'For developers, engineers, and tech enthusiasts. Code, collaborate, create.',
    cover_url: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Technology',
    members_count: 9800,
    posts_count: 4230,
    is_featured: false,
    is_paid: true,
    price: 5.00,
    is_joined: false,
  },
  {
    id: '5',
    name: 'Singles & Dating',
    description: 'A safe space for singles to connect, share experiences, and find meaningful relationships.',
    cover_url: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Relationships',
    members_count: 23400,
    posts_count: 12800,
    is_featured: true,
    is_paid: false,
    is_joined: false,
  },
  {
    id: '6',
    name: 'Creative Arts Collective',
    description: 'Musicians, artists, designers, and creatives sharing their work and inspiring each other.',
    cover_url: 'https://images.pexels.com/photos/1285625/pexels-photo-1285625.jpeg?auto=compress&cs=tinysrgb&w=800',
    avatar_url: 'https://images.pexels.com/photos/1646953/pexels-photo-1646953.jpeg?auto=compress&cs=tinysrgb&w=150',
    category: 'Art',
    members_count: 6700,
    posts_count: 3100,
    is_featured: false,
    is_paid: false,
    is_joined: false,
  },
];

export const MOCK_EVENTS = [
  {
    id: '1',
    title: 'Startup Kampala Networking Night',
    description: 'Join 200+ entrepreneurs for an evening of networking, pitching, and collaboration in the heart of Kampala.',
    cover_url: 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=800',
    event_type: 'professional',
    location: 'Serena Hotel, Kampala',
    is_online: false,
    starts_at: '2026-07-15T18:00:00',
    is_paid: true,
    ticket_price: 15,
    attendees_count: 187,
    max_attendees: 250,
    host: MOCK_USERS[4],
    is_featured: true,
    is_attending: false,
    category: 'Business',
  },
  {
    id: '2',
    title: 'Fitness Challenge Kickoff',
    description: '30-day transformation challenge. Free entry. All fitness levels welcome.',
    cover_url: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800',
    event_type: 'social',
    location: 'Online',
    is_online: true,
    starts_at: '2026-07-01T07:00:00',
    is_paid: false,
    attendees_count: 892,
    host: MOCK_USERS[2],
    is_featured: false,
    is_attending: true,
    category: 'Fitness',
  },
  {
    id: '3',
    title: 'Speed Friendship Nairobi',
    description: 'Meet 30 new people in 90 minutes! Our signature speed friendship event returns to Nairobi.',
    cover_url: 'https://images.pexels.com/photos/1267244/pexels-photo-1267244.jpeg?auto=compress&cs=tinysrgb&w=800',
    event_type: 'social',
    location: 'Hub Nairobi, Kenya',
    is_online: false,
    starts_at: '2026-07-20T15:00:00',
    is_paid: true,
    ticket_price: 10,
    attendees_count: 48,
    max_attendees: 60,
    host: MOCK_USERS[0],
    is_featured: true,
    is_attending: false,
    category: 'Social',
  },
  {
    id: '4',
    title: 'Africa Tech Summit 2026',
    description: 'The biggest tech conference in Africa. 3 days, 100+ speakers, 5000+ attendees.',
    cover_url: 'https://images.pexels.com/photos/2833037/pexels-photo-2833037.jpeg?auto=compress&cs=tinysrgb&w=800',
    event_type: 'professional',
    location: 'CTICC, Cape Town',
    is_online: false,
    starts_at: '2026-08-10T09:00:00',
    is_paid: true,
    ticket_price: 99,
    attendees_count: 3240,
    host: MOCK_USERS[1],
    is_featured: true,
    is_attending: false,
    category: 'Technology',
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: '1',
    type: 'direct',
    participant: MOCK_USERS[0],
    last_message: 'See you at the event tomorrow!',
    last_message_at: '2m ago',
    unread_count: 2,
    is_online: true,
  },
  {
    id: '2',
    type: 'direct',
    participant: MOCK_USERS[1],
    last_message: 'That is a great idea for the startup!',
    last_message_at: '15m ago',
    unread_count: 0,
    is_online: true,
  },
  {
    id: '3',
    type: 'direct',
    participant: MOCK_USERS[2],
    last_message: 'Thanks for the fitness tips!',
    last_message_at: '1h ago',
    unread_count: 1,
    is_online: false,
  },
  {
    id: '4',
    type: 'group',
    name: 'Entrepreneurs Uganda',
    avatar_url: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=150',
    last_message: 'Marcus: New post in the community',
    last_message_at: '3h ago',
    unread_count: 5,
    participants_count: 8420,
  },
  {
    id: '5',
    type: 'direct',
    participant: MOCK_USERS[4],
    last_message: 'Invest in relationships, not just capital.',
    last_message_at: '1d ago',
    unread_count: 0,
    is_online: false,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    type: 'like',
    title: 'Sarah Jones liked your post',
    body: '"Just closed our seed round..."',
    actor: MOCK_USERS[0],
    is_read: false,
    created_at: '2m ago',
  },
  {
    id: '2',
    type: 'friend_request',
    title: 'Marcus Chen sent you a friend request',
    body: 'Product designer from Accra, Ghana',
    actor: MOCK_USERS[3],
    is_read: false,
    created_at: '15m ago',
  },
  {
    id: '3',
    type: 'comment',
    title: 'Priya Sharma commented on your post',
    body: 'This is so inspiring! Count me in for the challenge!',
    actor: MOCK_USERS[2],
    is_read: false,
    created_at: '1h ago',
  },
  {
    id: '4',
    type: 'event',
    title: 'Event reminder: Startup Kampala Networking Night',
    body: 'Your event starts tomorrow at 6:00 PM',
    is_read: true,
    created_at: '3h ago',
  },
  {
    id: '5',
    type: 'community',
    title: 'New post in Entrepreneurs Uganda',
    body: 'Amina Diallo posted: "Funding opportunities for African startups"',
    actor: MOCK_USERS[4],
    is_read: true,
    created_at: '5h ago',
  },
  {
    id: '6',
    type: 'follow',
    title: 'James Okafor started following you',
    actor: MOCK_USERS[5],
    is_read: true,
    created_at: '1d ago',
  },
];

export const MOCK_CHAT_MESSAGES = [
  {
    id: '1',
    sender: MOCK_USERS[0],
    content: 'Hey! I saw your post about the startup round. Congratulations!',
    is_mine: false,
    created_at: '10:32 AM',
  },
  {
    id: '2',
    sender: null,
    content: 'Thank you so much! It has been a long journey but we made it!',
    is_mine: true,
    created_at: '10:34 AM',
  },
  {
    id: '3',
    sender: MOCK_USERS[0],
    content: 'That is amazing! What sector are you in?',
    is_mine: false,
    created_at: '10:35 AM',
  },
  {
    id: '4',
    sender: null,
    content: 'FinTech! We are building infrastructure for mobile money transfers across Africa.',
    is_mine: true,
    created_at: '10:37 AM',
  },
  {
    id: '5',
    sender: MOCK_USERS[0],
    content: 'Wow that is so relevant right now. We should connect in person! I am organizing a networking event next week.',
    is_mine: false,
    created_at: '10:39 AM',
  },
  {
    id: '6',
    sender: null,
    content: 'Absolutely! Send me the details. I would love to come.',
    is_mine: true,
    created_at: '10:40 AM',
  },
  {
    id: '7',
    sender: MOCK_USERS[0],
    content: 'See you at the event tomorrow!',
    is_mine: false,
    created_at: '2m ago',
  },
];
